version: '3.8'

services:
  backend:
    build: .
    container_name: spendly-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - .env

  db:
    image: postgres:16
    container_name: spendly-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: spendly_db
      POSTGRES_USER: spendly_user
      POSTGRES_PASSWORD: spendly123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
