services:
  db:
    image: postgres:15
    restart: always
    container_name: spendly_db
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: spendly
    restart: always
    ports:
      - "${PORT}:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      APPLICATION_SECRET: ${APPLICATION_SECRET}
      APPLICATION_URL: ${APPLICATION_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      DOCS_PASSWORD: ${DOCS_PASSWORD}
    volumes:
      - .:/app
    command: npm run dev

volumes:
  postgres_data:

