import { TransactionType, PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Deliberately upserted by `name` (see main() below), never deleted - a
// category already referenced by a user's real transactions must keep
// existing. That's why broad categories from the original list (Food,
// Transportation, Subscriptions, Entertainment, Home Goods, Gifts...) stay
// as-is rather than being renamed or split in place: each now sits alongside
// new, more specific siblings (Food -> also Groceries/Restaurants/Coffee
// Shops/...) and doubles as the catch-all when the AI or the user can't be
// more precise. `order` is safe to renumber freely across the whole list on
// every deploy since it's just a display-sort column, not the upsert key.
const categories = [
  // ─── Income ───────────────────────────────────────────────────────────
  {
    name: 'Salary',
    nameRu: 'Зарплата',
    color: '#16A34A',
    type: TransactionType.INCOME,
    order: 1,
  },
  {
    name: 'Freelance',
    nameRu: 'Фриланс',
    color: '#4ADE80',
    type: TransactionType.INCOME,
    order: 2,
  },
  {
    name: 'Business Income',
    nameRu: 'Доход от бизнеса',
    color: '#059669',
    type: TransactionType.INCOME,
    order: 3,
  },
  {
    name: 'Bonus',
    nameRu: 'Бонус',
    color: '#22C55E',
    type: TransactionType.INCOME,
    order: 4,
  },
  {
    name: 'Side Hustle',
    nameRu: 'Подработка',
    color: '#10B981',
    type: TransactionType.INCOME,
    order: 5,
  },
  {
    name: 'Investments',
    nameRu: 'Инвестиции',
    color: '#0EA5E9',
    type: TransactionType.INCOME,
    order: 6,
  },
  {
    name: 'Dividends',
    nameRu: 'Дивиденды',
    color: '#0284C7',
    type: TransactionType.INCOME,
    order: 7,
  },
  {
    name: 'Interest',
    nameRu: 'Проценты',
    color: '#0369A1',
    type: TransactionType.INCOME,
    order: 8,
  },
  {
    name: 'Rental Income',
    nameRu: 'Доход от аренды',
    color: '#0891B2',
    type: TransactionType.INCOME,
    order: 9,
  },
  {
    name: 'Pension',
    nameRu: 'Пенсия',
    color: '#0E7490',
    type: TransactionType.INCOME,
    order: 10,
  },
  {
    name: 'Government Benefits',
    nameRu: 'Государственные пособия',
    color: '#06B6D4',
    type: TransactionType.INCOME,
    order: 11,
  },
  {
    name: 'Cashback & Rewards',
    nameRu: 'Кэшбэк и бонусы',
    color: '#A3E635',
    type: TransactionType.INCOME,
    order: 12,
  },
  {
    name: 'Sold Items',
    nameRu: 'Продажа вещей',
    color: '#84CC16',
    type: TransactionType.INCOME,
    order: 13,
  },
  {
    name: 'Refunds',
    nameRu: 'Возвраты',
    color: '#8B5CF6',
    type: TransactionType.INCOME,
    order: 14,
  },
  {
    name: 'Gifts Received',
    nameRu: 'Полученные подарки',
    color: '#EC4899',
    type: TransactionType.INCOME,
    order: 15,
  },

  // ─── Expense: Food & Drink ────────────────────────────────────────────
  {
    name: 'Food',
    nameRu: 'Еда',
    color: '#22C55E',
    type: TransactionType.EXPENSE,
    order: 16,
  },
  {
    name: 'Groceries',
    nameRu: 'Продукты',
    color: '#16A34A',
    type: TransactionType.EXPENSE,
    order: 17,
  },
  {
    name: 'Restaurants',
    nameRu: 'Рестораны',
    color: '#15803D',
    type: TransactionType.EXPENSE,
    order: 18,
  },
  {
    name: 'Coffee Shops',
    nameRu: 'Кофейни',
    color: '#92400E',
    type: TransactionType.EXPENSE,
    order: 19,
  },
  {
    name: 'Fast Food',
    nameRu: 'Фастфуд',
    color: '#EA580C',
    type: TransactionType.EXPENSE,
    order: 20,
  },
  {
    name: 'Food Delivery',
    nameRu: 'Доставка еды',
    color: '#FB923C',
    type: TransactionType.EXPENSE,
    order: 21,
  },
  {
    name: 'Bars & Nightlife',
    nameRu: 'Бары и ночная жизнь',
    color: '#C026D3',
    type: TransactionType.EXPENSE,
    order: 22,
  },
  {
    name: 'Alcohol & Tobacco',
    nameRu: 'Алкоголь и табак',
    color: '#7E22CE',
    type: TransactionType.EXPENSE,
    order: 23,
  },

  // ─── Expense: Housing ─────────────────────────────────────────────────
  {
    name: 'Rent',
    nameRu: 'Аренда',
    color: '#EF4444',
    type: TransactionType.EXPENSE,
    order: 24,
  },
  {
    name: 'Utilities',
    nameRu: 'Коммунальные услуги',
    color: '#F97316',
    type: TransactionType.EXPENSE,
    order: 25,
  },
  {
    name: 'Internet & Phone',
    nameRu: 'Интернет и связь',
    color: '#FB923C',
    type: TransactionType.EXPENSE,
    order: 26,
  },
  {
    name: 'Home Insurance',
    nameRu: 'Страхование жилья',
    color: '#DC2626',
    type: TransactionType.EXPENSE,
    order: 27,
  },
  {
    name: 'Furniture',
    nameRu: 'Мебель',
    color: '#78716C',
    type: TransactionType.EXPENSE,
    order: 28,
  },
  {
    name: 'Home Repairs',
    nameRu: 'Ремонт дома',
    color: '#A16207',
    type: TransactionType.EXPENSE,
    order: 29,
  },
  {
    name: 'Cleaning Services',
    nameRu: 'Клининг',
    color: '#0D9488',
    type: TransactionType.EXPENSE,
    order: 30,
  },

  // ─── Expense: Transportation ──────────────────────────────────────────
  {
    name: 'Transportation',
    nameRu: 'Транспорт',
    color: '#14B8A6',
    type: TransactionType.EXPENSE,
    order: 31,
  },
  {
    name: 'Fuel',
    nameRu: 'Топливо',
    color: '#0D9488',
    type: TransactionType.EXPENSE,
    order: 32,
  },
  {
    name: 'Public Transport',
    nameRu: 'Общественный транспорт',
    color: '#0F766E',
    type: TransactionType.EXPENSE,
    order: 33,
  },
  {
    name: 'Taxi / Ride Sharing',
    nameRu: 'Такси',
    color: '#2DD4BF',
    type: TransactionType.EXPENSE,
    order: 34,
  },
  {
    name: 'Car Maintenance',
    nameRu: 'Обслуживание авто',
    color: '#7C2D12',
    type: TransactionType.EXPENSE,
    order: 35,
  },
  {
    name: 'Car Insurance',
    nameRu: 'Автостраховка',
    color: '#991B1B',
    type: TransactionType.EXPENSE,
    order: 36,
  },
  {
    name: 'Parking',
    nameRu: 'Парковка',
    color: '#9CA3AF',
    type: TransactionType.EXPENSE,
    order: 37,
  },
  {
    name: 'Flights',
    nameRu: 'Авиабилеты',
    color: '#38BDF8',
    type: TransactionType.EXPENSE,
    order: 38,
  },

  // ─── Expense: Health ──────────────────────────────────────────────────
  {
    name: 'Doctor / Medical',
    nameRu: 'Медицина',
    color: '#DB2777',
    type: TransactionType.EXPENSE,
    order: 39,
  },
  {
    name: 'Dental',
    nameRu: 'Стоматология',
    color: '#F472B6',
    type: TransactionType.EXPENSE,
    order: 40,
  },
  {
    name: 'Health Insurance',
    nameRu: 'Медицинская страховка',
    color: '#BE185D',
    type: TransactionType.EXPENSE,
    order: 41,
  },
  {
    name: 'Pharmacy',
    nameRu: 'Аптека',
    color: '#EC4899',
    type: TransactionType.EXPENSE,
    order: 42,
  },
  {
    name: 'Gym',
    nameRu: 'Спортзал',
    color: '#7C3AED',
    type: TransactionType.EXPENSE,
    order: 43,
  },

  // ─── Expense: Personal ────────────────────────────────────────────────
  {
    name: 'Clothing',
    nameRu: 'Одежда',
    color: '#8B5CF6',
    type: TransactionType.EXPENSE,
    order: 44,
  },
  {
    name: 'Shoes',
    nameRu: 'Обувь',
    color: '#7C3AED',
    type: TransactionType.EXPENSE,
    order: 45,
  },
  {
    name: 'Personal Care',
    nameRu: 'Уход за собой',
    color: '#D946EF',
    type: TransactionType.EXPENSE,
    order: 46,
  },
  {
    name: 'Haircut & Beauty',
    nameRu: 'Парикмахерская и салон красоты',
    color: '#E879F9',
    type: TransactionType.EXPENSE,
    order: 47,
  },

  // ─── Expense: Home Goods & Tech ───────────────────────────────────────
  {
    name: 'Home Goods',
    nameRu: 'Товары для дома',
    color: '#3B82F6',
    type: TransactionType.EXPENSE,
    order: 48,
  },
  {
    name: 'Electronics',
    nameRu: 'Электроника',
    color: '#2563EB',
    type: TransactionType.EXPENSE,
    order: 49,
  },

  // ─── Expense: Family ──────────────────────────────────────────────────
  {
    name: 'Gifts',
    nameRu: 'Подарки',
    color: '#F472B6',
    type: TransactionType.EXPENSE,
    order: 50,
  },
  {
    name: 'Childcare',
    nameRu: 'Уход за детьми',
    color: '#FB7185',
    type: TransactionType.EXPENSE,
    order: 51,
  },
  {
    name: 'Kids & Baby',
    nameRu: 'Дети и товары для малышей',
    color: '#FDA4AF',
    type: TransactionType.EXPENSE,
    order: 52,
  },
  {
    name: 'Pets',
    nameRu: 'Питомцы',
    color: '#A855F7',
    type: TransactionType.EXPENSE,
    order: 53,
  },

  // ─── Expense: Subscriptions & Software ────────────────────────────────
  {
    name: 'Subscriptions',
    nameRu: 'Подписки',
    color: '#6366F1',
    type: TransactionType.EXPENSE,
    order: 54,
  },
  {
    name: 'Streaming Services',
    nameRu: 'Стриминг-сервисы',
    color: '#4F46E5',
    type: TransactionType.EXPENSE,
    order: 55,
  },
  {
    name: 'Software / Cloud Services',
    nameRu: 'Программы и облако',
    color: '#0284C7',
    type: TransactionType.EXPENSE,
    order: 56,
  },

  // ─── Expense: Education ───────────────────────────────────────────────
  {
    name: 'Education',
    nameRu: 'Образование',
    color: '#14B8A6',
    type: TransactionType.EXPENSE,
    order: 57,
  },
  {
    name: 'Online Courses',
    nameRu: 'Онлайн-курсы',
    color: '#22D3EE',
    type: TransactionType.EXPENSE,
    order: 58,
  },
  {
    name: 'Books',
    nameRu: 'Книги',
    color: '#0D9488',
    type: TransactionType.EXPENSE,
    order: 59,
  },

  // ─── Expense: Entertainment & Leisure ─────────────────────────────────
  {
    name: 'Entertainment',
    nameRu: 'Развлечения',
    color: '#F472B6',
    type: TransactionType.EXPENSE,
    order: 60,
  },
  {
    name: 'Movies & Cinema',
    nameRu: 'Кино',
    color: '#C084FC',
    type: TransactionType.EXPENSE,
    order: 61,
  },
  {
    name: 'Hobbies',
    nameRu: 'Хобби',
    color: '#A78BFA',
    type: TransactionType.EXPENSE,
    order: 62,
  },
  {
    name: 'Games',
    nameRu: 'Игры',
    color: '#818CF8',
    type: TransactionType.EXPENSE,
    order: 63,
  },
  {
    name: 'Travel',
    nameRu: 'Путешествия',
    color: '#38BDF8',
    type: TransactionType.EXPENSE,
    order: 64,
  },
  {
    name: 'Events',
    nameRu: 'Мероприятия',
    color: '#F0ABFC',
    type: TransactionType.EXPENSE,
    order: 65,
  },

  // ─── Expense: Finance & Obligations ───────────────────────────────────
  {
    name: 'Taxes',
    nameRu: 'Налоги',
    color: '#991B1B',
    type: TransactionType.EXPENSE,
    order: 66,
  },
  {
    name: 'Loan / Credit Payments',
    nameRu: 'Кредиты',
    color: '#B91C1C',
    type: TransactionType.EXPENSE,
    order: 67,
  },
  {
    name: 'Bank Fees',
    nameRu: 'Банковские комиссии',
    color: '#7F1D1D',
    type: TransactionType.EXPENSE,
    order: 68,
  },
  {
    name: 'ATM / Cash Withdrawal',
    nameRu: 'Снятие наличных',
    color: '#57534E',
    type: TransactionType.EXPENSE,
    order: 69,
  },
  {
    name: 'Alimony & Child Support',
    nameRu: 'Алименты',
    color: '#78716C',
    type: TransactionType.EXPENSE,
    order: 70,
  },
  {
    name: 'Legal & Professional Services',
    nameRu: 'Юридические и проф. услуги',
    color: '#52525B',
    type: TransactionType.EXPENSE,
    order: 71,
  },

  // ─── Expense: Work & Misc ─────────────────────────────────────────────
  {
    name: 'Work Expenses',
    nameRu: 'Рабочие расходы',
    color: '#64748B',
    type: TransactionType.EXPENSE,
    order: 72,
  },
  {
    name: 'Charity',
    nameRu: 'Благотворительность',
    color: '#22C55E',
    type: TransactionType.EXPENSE,
    order: 73,
  },
  {
    name: 'Unexpected Expenses',
    nameRu: 'Непредвиденные расходы',
    color: '#6B7280',
    type: TransactionType.EXPENSE,
    order: 74,
  },
];

const currencies = [
  { code: 'AED', name: 'United Arab Emirates Dirham' },
  { code: 'AFN', name: 'Afghan Afghani' },
  { code: 'ALL', name: 'Albanian Lek' },
  { code: 'AMD', name: 'Armenian Dram' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder' },
  { code: 'AOA', name: 'Angolan Kwanza' },
  { code: 'ARS', name: 'Argentine Peso' },
  { code: 'AUD', name: 'Australian Dollar' },
  { code: 'AWG', name: 'Aruban Florin' },
  { code: 'AZN', name: 'Azerbaijani Manat' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark' },
  { code: 'BBD', name: 'Barbadian Dollar' },
  { code: 'BDT', name: 'Bangladeshi Taka' },
  { code: 'BGN', name: 'Bulgarian Lev' },
  { code: 'BHD', name: 'Bahraini Dinar' },
  { code: 'BIF', name: 'Burundian Franc' },
  { code: 'BMD', name: 'Bermudian Dollar' },
  { code: 'BND', name: 'Brunei Dollar' },
  { code: 'BOB', name: 'Bolivian Boliviano' },
  { code: 'BRL', name: 'Brazilian Real' },
  { code: 'BSD', name: 'Bahamian Dollar' },
  { code: 'BWP', name: 'Botswanan Pula' },
  { code: 'BYN', name: 'Belarusian Ruble' },
  { code: 'BZD', name: 'Belize Dollar' },
  { code: 'CAD', name: 'Canadian Dollar' },
  { code: 'CDF', name: 'Congolese Franc' },
  { code: 'CHF', name: 'Swiss Franc' },
  { code: 'CLP', name: 'Chilean Peso' },
  { code: 'CNY', name: 'Chinese Yuan' },
  { code: 'COP', name: 'Colombian Peso' },
  { code: 'CRC', name: 'Costa Rican Colón' },
  { code: 'CUP', name: 'Cuban Peso' },
  { code: 'CVE', name: 'Cape Verdean Escudo' },
  { code: 'CZK', name: 'Czech Koruna' },
  { code: 'DJF', name: 'Djiboutian Franc' },
  { code: 'DKK', name: 'Danish Krone' },
  { code: 'DOP', name: 'Dominican Peso' },
  { code: 'DZD', name: 'Algerian Dinar' },
  { code: 'EGP', name: 'Egyptian Pound' },
  { code: 'ERN', name: 'Eritrean Nakfa' },
  { code: 'ETB', name: 'Ethiopian Birr' },
  { code: 'EUR', name: 'Euro' },
  { code: 'FJD', name: 'Fijian Dollar' },
  { code: 'FKP', name: 'Falkland Islands Pound' },
  { code: 'GBP', name: 'British Pound Sterling' },
  { code: 'GEL', name: 'Georgian Lari' },
  { code: 'GHS', name: 'Ghanaian Cedi' },
  { code: 'GIP', name: 'Gibraltar Pound' },
  { code: 'GMD', name: 'Gambian Dalasi' },
  { code: 'GNF', name: 'Guinean Franc' },
  { code: 'GTQ', name: 'Guatemalan Quetzal' },
  { code: 'GYD', name: 'Guyanaese Dollar' },
  { code: 'HKD', name: 'Hong Kong Dollar' },
  { code: 'HNL', name: 'Honduran Lempira' },
  { code: 'HRK', name: 'Croatian Kuna' },
  { code: 'HTG', name: 'Haitian Gourde' },
  { code: 'HUF', name: 'Hungarian Forint' },
  { code: 'IDR', name: 'Indonesian Rupiah' },
  { code: 'ILS', name: 'Israeli New Shekel' },
  { code: 'INR', name: 'Indian Rupee' },
  { code: 'IQD', name: 'Iraqi Dinar' },
  { code: 'IRR', name: 'Iranian Rial' },
  { code: 'ISK', name: 'Icelandic Króna' },
  { code: 'JMD', name: 'Jamaican Dollar' },
  { code: 'JOD', name: 'Jordanian Dinar' },
  { code: 'JPY', name: 'Japanese Yen' },
  { code: 'KES', name: 'Kenyan Shilling' },
  { code: 'KGS', name: 'Kyrgystani Som' },
  { code: 'KHR', name: 'Cambodian Riel' },
  { code: 'KMF', name: 'Comorian Franc' },
  { code: 'KPW', name: 'North Korean Won' },
  { code: 'KRW', name: 'South Korean Won' },
  { code: 'KWD', name: 'Kuwaiti Dinar' },
  { code: 'KYD', name: 'Cayman Islands Dollar' },
  { code: 'KZT', name: 'Kazakhstani Tenge' },
  { code: 'LAK', name: 'Laotian Kip' },
  { code: 'LBP', name: 'Lebanese Pound' },
  { code: 'LKR', name: 'Sri Lankan Rupee' },
  { code: 'LRD', name: 'Liberian Dollar' },
  { code: 'LSL', name: 'Lesotho Loti' },
  { code: 'LYD', name: 'Libyan Dinar' },
  { code: 'MAD', name: 'Moroccan Dirham' },
  { code: 'MDL', name: 'Moldovan Leu' },
  { code: 'MGA', name: 'Malagasy Ariary' },
  { code: 'MKD', name: 'Macedonian Denar' },
  { code: 'MMK', name: 'Myanma Kyat' },
  { code: 'MNT', name: 'Mongolian Tugrik' },
  { code: 'MOP', name: 'Macanese Pataca' },
  { code: 'MRU', name: 'Mauritanian Ouguiya' },
  { code: 'MUR', name: 'Mauritian Rupee' },
  { code: 'MVR', name: 'Maldivian Rufiyaa' },
  { code: 'MWK', name: 'Malawian Kwacha' },
  { code: 'MXN', name: 'Mexican Peso' },
  { code: 'MYR', name: 'Malaysian Ringgit' },
  { code: 'MZN', name: 'Mozambican Metical' },
  { code: 'NAD', name: 'Namibian Dollar' },
  { code: 'NGN', name: 'Nigerian Naira' },
  { code: 'NIO', name: 'Nicaraguan Córdoba' },
  { code: 'NOK', name: 'Norwegian Krone' },
  { code: 'NPR', name: 'Nepalese Rupee' },
  { code: 'NZD', name: 'New Zealand Dollar' },
  { code: 'OMR', name: 'Omani Rial' },
  { code: 'PAB', name: 'Panamanian Balboa' },
  { code: 'PEN', name: 'Peruvian Nuevo Sol' },
  { code: 'PGK', name: 'Papua New Guinean Kina' },
  { code: 'PHP', name: 'Philippine Peso' },
  { code: 'PKR', name: 'Pakistani Rupee' },
  { code: 'PLN', name: 'Polish Zloty' },
  { code: 'PYG', name: 'Paraguayan Guarani' },
  { code: 'QAR', name: 'Qatari Rial' },
  { code: 'RON', name: 'Romanian Leu' },
  { code: 'RSD', name: 'Serbian Dinar' },
  { code: 'RUB', name: 'Russian Ruble' },
  { code: 'RWF', name: 'Rwandan Franc' },
  { code: 'SAR', name: 'Saudi Riyal' },
  { code: 'SBD', name: 'Solomon Islands Dollar' },
  { code: 'SCR', name: 'Seychellois Rupee' },
  { code: 'SDG', name: 'Sudanese Pound' },
  { code: 'SEK', name: 'Swedish Krona' },
  { code: 'SGD', name: 'Singapore Dollar' },
  { code: 'SHP', name: 'Saint Helena Pound' },
  { code: 'SLE', name: 'Sierra Leonean Leone' },
  { code: 'SOS', name: 'Somali Shilling' },
  { code: 'SRD', name: 'Surinamese Dollar' },
  { code: 'SSP', name: 'South Sudanese Pound' },
  { code: 'SYP', name: 'Syrian Pound' },
  { code: 'SZL', name: 'Swazi Lilangeni' },
  { code: 'THB', name: 'Thai Baht' },
  { code: 'TJS', name: 'Tajikistani Somoni' },
  { code: 'TMT', name: 'Turkmenistani Manat' },
  { code: 'TND', name: 'Tunisian Dinar' },
  { code: 'TOP', name: 'Tongan Paʻanga' },
  { code: 'TRY', name: 'Turkish Lira' },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar' },
  { code: 'TWD', name: 'New Taiwan Dollar' },
  { code: 'TZS', name: 'Tanzanian Shilling' },
  { code: 'UAH', name: 'Ukrainian Hryvnia' },
  { code: 'UGX', name: 'Ugandan Shilling' },
  { code: 'USD', name: 'United States Dollar' },
  { code: 'UYU', name: 'Uruguayan Peso' },
  { code: 'UZS', name: 'Uzbekistan Som' },
  { code: 'VES', name: 'Venezuelan Bolívar' },
  { code: 'VND', name: 'Vietnamese Dong' },
  { code: 'VUV', name: 'Vanuatu Vatu' },
  { code: 'WST', name: 'Samoan Tala' },
  { code: 'XAF', name: 'Central African CFA Franc' },
  { code: 'XCD', name: 'East Caribbean Dollar' },
  { code: 'XOF', name: 'West African CFA Franc' },
  { code: 'XPF', name: 'CFP Franc' },
  { code: 'YER', name: 'Yemeni Rial' },
  { code: 'ZAR', name: 'South African Rand' },
  { code: 'ZMW', name: 'Zambian Kwacha' },
  { code: 'ZWL', name: 'Zimbabwean Dollar' },
];

async function main() {
  console.log('🌱 Seeding currencies...');

  await prisma.currency.createMany({
    data: currencies,
    skipDuplicates: true,
  });

  console.log(`✅ Seeded ${currencies.length} currencies`);

  console.log('🌱 Seeding categories...');

  for (const category of categories) {
    await prisma.category.upsert({
      where: { name: category.name },
      update: {
        nameRu: category.nameRu,
        color: category.color,
        type: category.type,
        order: category.order,
      },
      create: category,
    });
  }

  console.log(`✅ Seeded ${categories.length} categories`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
